const LANG = {
  en: {
    title: "Aniimo Patch Notes",
    searchPlaceholder: "Search Aniimo...",
    selectAniimo: "Select an Aniimo.",
    hoverIconDetails: "Move your mouse over an icon to show its details.",

    versionSubtitle: "Closed Beta 2 → Closed Beta 3",
    patchSummary: "Patch Summary",
    aniilogIntro: "Explore all Aniimos from the current version.",

    stats: "Stats",
    baseStats: "Base Stats",
    traits: "Traits",
    traitsSingular: "Trait",
    spells: "Spells",
    spellsSingular: "Spell",
    ultimate: "Ultimate",
    ultimateSingular: "Ultimate",
    forms: "Forms",
    formsSingular: "Form",
    prismana: "Prismana",
    prismanaSingular: "Prismana",
    fire: "Fire",
    water: "Water",
    grass: "Grass",
    earth: "Earth",
    ice: "Ice",
    wind: "Wind",
    lightning: "Lightning",
    dark: "Dark",
    light: "Light",
    DPS: "DPS",
    break: "Break",
    regen: "Regen",
    heal: "Heal",
    support: "Support",

    base: "Base",

    name: "Name",
    type: "Type",
    role: "Role",
    cost: "Cost",
    cooldown: "Cooldown",
    energy: "Energy",
    energyPoints: "Energy Points",
    duration: "Duration",
    power: "Power",
    damageType: "Damage Type",
    bonus: "Bonus",
    malus: "Malus",
    heal: "Heal",
    shield: "Shield",
    control: "Control",
    regenEp: "EP regeneration",

    removed: "Removed",
    modified: "Modified",
    new: "New",
    before: "Before",
    after: "After",
    advancedSearch: "Advanced search",
    sortBy: "Sort by",

    newAniimo: "New Aniimo",
    summaryAdded: "added",
    summaryModified: "modified",
    summaryRemoved: "removed",
    all: "All",
    types: "Types",
    roles: "Roles",
    tags : "Tags",
    physical: "Physical",
    magical: "Magical",
    support: "Support",
  },

  fr: {
    title: "Aniimo Notes de Patch",
    searchPlaceholder: "Chercher un Aniimo...",
    selectAniimo: "Sélectionnez un Aniimo.",
    hoverIconDetails: "Survolez une icône pour afficher ses détails.",

    versionSubtitle: "Bêta fermée 2 → Bêta fermée 3",
    patchSummary: "Résumé du patch",
    aniilogIntro: "Explorez tous les Aniimos de la version actuelle.",

    stats: "Statistiques",
    baseStats: "Total des stats",
    traits: "Talent",
    traitsSingular: "talent",
    spells: "Sorts",
    spellsSingular: "sort",
    ultimate: "Ultime",
    ultimateSingular: "ultime",
    forms: "Formes",
    formsSingular: "forme",
    prismana: "Prismana",
    prismanaSingular: "Prismana",
    fire: "Feu",
water: "Eau",
grass: "Plante",
earth: "Terre",
ice: "Glace",
wind: "Vent",
lightning: "Foudre",
dark: "Ténèbres",
light: "Lumière",
DPS: "DPS",
break: "Break",
regenEP: "Régen EP",
heal: "Soin",
    support: "Support",

    base: "Base",

    name: "Nom",
    type: "Type",
    role: "Rôle",
    cost: "Coût",
    cooldown: "Temps de recharge",
    energy: "Énergie",
    energyPoints: "Points d'énergie",
    duration: "Durée",
    power: "Puissance",
    damageType: "Type de dégâts",
    bonus: "Bonus",
    malus: "Malus",
    heal: "Soin",
    shield: "Bouclier",
    control: "Contrôle",
    regenEp: "Régénération d’EP",

    removed: "Retiré",
    modified: "Modifié",
    new: "Nouveau",
    before: "Avant",
    after: "Après",
    advancedSearch: "Recherche avancée",
    sortBy: "Trier par",

    newAniimo: "Nouvel Aniimo",
    summaryAdded: "ajouté",
    summaryModified: "modifié",
    summaryRemoved: "retiré",

    all: "Tous",
    types: "Types",
    roles: "Rôles",
    tags: "Tags",
    physical: "Physique",
    magical: "Magique",
    support: "Support",
  }
};
